services:
  controller-1:
    image: confluentinc/cp-kafka
    container_name: controller-1
    networks:
      - kafka-network
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      CLUSTER_ID: "SCARRAFONE"
    volumes:
      - controller-1-data:/bitnami/kafka

  controller-2:
    image: confluentinc/cp-kafka
    container_name: controller-2
    networks:
      - kafka-network
    ports:
      - "9094:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      CLUSTER_ID: "SCARRAFONE"
    volumes:
      - controller-2-data:/bitnami/kafka

  controller-3:
    image: confluentinc/cp-kafka
    container_name: controller-3
    networks:
      - kafka-network
    ports:
      - "9095:9093"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      CLUSTER_ID: "SCARRAFONE"
    volumes:
      - controller-3-data:/bitnami/kafka

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "SCARRAFONE"
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    volumes:
      - broker-data:/bitnami/kafka
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "broker:9092" ]
      start_period: 20s
      interval: 5s
      timeout: 30s
      retries: 5

  producer:
    build:
      context: ./producer
    container_name: producer
    networks:
      - kafka-network
    volumes:
      - ./producer/logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
    depends_on:
      broker:
        condition: service_healthy

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    networks:
      - kafka-network
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
    depends_on:
      broker:
        condition: service_healthy

  asmeta-server:
    build:
      context: ./external/ASMeta/asmeta_server
      dockerfile: Dockerfile
    container_name: asmeta-server
    networks:
      - asmeta-server
    ports:
      - "8080:8080"

  asm1:
    build:
      context: ./ASM-ex1
      dockerfile: Dockerfile
    container_name: asm1
    networks:
      - kafka-network
    volumes:
      - ./ASM-ex1/log:/app/log
      - ./ASM-ex1/config.json:/app/config.json
    depends_on:
      - asmeta-server
    stdin_open: true
    tty: true

networks:
  kafka-network:
    driver: bridge
  asmeta-server:
    driver: bridge

volumes:
  controller-1-data:
  controller-2-data:
  controller-3-data:
  broker-data: