
site_name: Kafka-DigitalTwins Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Riferimento Codice:
      - ASM-ex1: code_reference/asm1.md
      - ASM-ex2: code_reference/asm2.md
      - ASM-ex3: code_reference/asm3.md
      - Moduli Condivisi: code_reference/shared_modules.md

plugins:
  - search
  - mermaid2     # abilita il rendering dei diagrammi Mermaid

markdown_extensions:
  - admonition
  - pymdownx.superfences   # necessario per i blocchi ```mermaid
  - pymdownx.highlight
